### ISSUE TITLE
Build admin view for individual commissions

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Commissions#148] opened 2016-09-08 18:21 UTC
This would be similar to what was added for single license views:
https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/667

And also similar to what was done for Recurring, Customer, and Vendor profiles.

It could show information about the commission such as:
- Customer
- Vendor/Reciever
- Date of initial purchase
- Date of actual Commission payment
- Amount
- Rate (%)
- Product(s) purchased
- Special notes about the commission
- Any additional custom meta

**Comment by pippinsplugins** [comment] 2016-10-26 20:05
@ghost1227 how're we coming here?

**Comment by ghost1227** [comment] 2016-10-26 20:09
Got it about halfway done then got refocussed on SL and kinda forgot to finish this. I'll try to get it pushed tomorrow.

**Comment by pippinsplugins** [comment] 2016-10-26 20:10
@ghost1227 go ahead and open a PR with WIP. Makes me easier to track :)

**Comment by ghost1227** [comment] 2016-10-26 20:11
Makes you easier to track? Why would anyone want to track Pippin? 😛

**Comment by pippinsplugins** [comment] 2016-10-26 20:15
:p

**Comment by ghost1227** [comment] 2016-10-27 15:11
@pippinsplugins Initial view code pushed as promised! Still a lot to do, thus far it's just adding the actions link, migrating code to the new view style, and creating the core of the view.

**Comment by pippinsplugins** [comment] 2016-10-27 15:14
@ghost1227 Great, go ahead and open a PR too. Email notifications of new commit pushes only get sent if a PR is open.

**Comment by ghost1227** [comment] 2016-10-27 15:15
Done

**Comment by ghost1227** [comment] 2017-01-06 17:22
@pippinsplugins I did a refresh and update of this earlier this morning... also changed how the top table is built. Not sure you're going to like it, but the redundancy and inflexibility was driving me nuts.

**Comment by pippinsplugins** [comment] 2017-01-06 19:56
@ghost1227 please go ahead and make a `release/3.3` branch and update the PR for that branch.

**Comment by pippinsplugins** [comment] 2017-01-06 19:59
@ghost1227 this view will also need to include edit capabilities.

**Comment by ghost1227** [comment] 2017-01-07 05:58
Oops, I actually built it against `release/3.3` but accidentally submitted against `master`. What all should be editable? Also, right now it's literally mimicking the functionality of the table itself... do we want to remove anything from the table?

**Comment by pippinsplugins** [comment] 2017-01-07 18:30
Take a look at the fields editable in `master`. Same ones need to be editable.

**Comment by ghost1227** [comment] 2017-01-09 20:33
@pippinsplugins Added field editing to the card view, along with core actions. `master` has functions for manually adding a commission, but I don't see any way of actually triggering that process?

**Comment by pippinsplugins** [comment] 2017-01-09 20:34
@ghost1227 There used to be an `Add New` button. Let's please go ahead and build that out too.

**Comment by ghost1227** [comment] 2017-01-09 20:35
Ok

**Comment by ghost1227** [comment] 2017-01-09 21:13
@pippinsplugins Done!

**Comment by pippinsplugins** [comment] 2017-01-09 21:18
@ghost1227 Could we get periods at the end of each field description on the screen please?
![screen shot 2017-01-09 at 3 17 57 pm](https://cloud.githubusercontent.com/assets/1034109/21783902/dd58ed76-d67e-11e6-9dff-f76d5cf0bbd0.png)

Also the add new screen needs to include a status drop down.

**Comment by pippinsplugins** [comment] 2017-01-09 21:19
Since we're here, let's go ahead and add chosen drop downs for the user and download fields please.

**Comment by ghost1227** [comment] 2017-01-09 21:19
Roger that!

**Comment by mintplugins** [comment] 2017-01-09 21:24
Could you add non-editable fields for the product and price id? I think it would be useful to admin checking to see for-which product the commission was generated.

**Comment by mintplugins** [comment] 2017-01-09 21:25
Oh and also the currency of the commission

**Comment by ghost1227** [comment] 2017-01-09 21:33
@mintplugins Product and price ID are there....

**Comment by ghost1227** [comment] 2017-01-09 21:38
Aren't currencies standardized to whatever EDD itself is set for?

**Comment by mintplugins** [comment] 2017-01-09 21:40
@ghost1227 Oh my bad. I see Download - is the Price ID included in that? Currencies for Commissions can be set individually. See:

https://github.com/easydigitaldownloads/EDD-Commissions/blob/57890b12edeb14da870bbc0a716102be5c697320/includes/integrations/paypal-adaptive-payments.php#L54

**Comment by ghost1227** [comment] 2017-01-09 21:42
@mintplugins yes, it includes price ID/variation when applicable.

**Comment by ghost1227** [comment] 2017-01-09 21:44
RE: currencies, I see that field in the AP integration (which is all but dead now given the recent PayPal changes), but I don't see a way to change/set that in the dashboard. As far as I can see, it's basically an unused field?

**Comment by ghost1227** [comment] 2017-01-09 21:47
@pippinsplugins Do we want to get rid of any of the existing table fields since the same exact data is duplicated in the card view now?

**Comment by mintplugins** [comment] 2017-01-10 01:31
It seem that some customers are using it in conjuntion with the Aelia Currency converter plugin - though I am not sure exactly how. This customer in particular: https://secure.helpscout.net/conversation/300213985/50215/?folderId=180504

**Comment by ghost1227** [comment] 2017-01-10 02:11
@pippinsplugins Thoughts on that?

**Comment by pippinsplugins** [comment] 2017-01-10 22:04
@ghost1227 No, I don't think any of the table data should be removed.

We do need to enable currency support.

**Comment by ghost1227** [comment] 2017-01-11 20:25
@pippinsplugins added currency field. Anything else?

**Comment by ghost1227** [comment] 2017-01-11 20:27
<img width="759" alt="screen shot 2017-01-11 at 2 26 55 pm" src="https://cloud.githubusercontent.com/assets/36433/21865052/0c25e9f6-d80a-11e6-9499-f3afbb0c88c7.png">

**Comment by pippinsplugins** [comment] 2017-01-11 20:30
Is having each field have a separate edit link too much? I think we should have a single edit button that reveals the fields for each item.

**Comment by ghost1227** [comment] 2017-01-11 20:31
Doesn't matter much to me. I added the individual edit links to keep it uniform with how the other cards are displayed.

**Comment by SDavisMedia** [comment] 2017-01-11 20:35
I'm with Pippin.

**Comment by pippinsplugins** [comment] 2017-01-25 17:03
@ghost1227 could we fix the "jump" that happens when clicking the edit link please?
![screen shot 2017-01-25 at 11 03 04 am](https://cloud.githubusercontent.com/assets/1034109/22300713/f4cf76c0-e2ed-11e6-807f-3480ed29db0b.png)
![screen shot 2017-01-25 at 11 03 10 am](https://cloud.githubusercontent.com/assets/1034109/22300714/f4d00f40-e2ed-11e6-87b7-e0fd22468511.png)

**Comment by pippinsplugins** [comment] 2017-01-25 17:04
Hard to see in those screenshots, but the edit view has the right column shifted to the left by about 10-20px.

**Comment by pippinsplugins** [comment] 2017-01-25 17:05
`Purchase Date` should be `Created Date`.

**Comment by pippinsplugins** [comment] 2017-01-25 17:05
Let's also please capitalize the first letter of the status value.

**Comment by ghost1227** [comment] 2017-01-25 17:27
I'm having a compatibility issue with 2.7+ card tabs that I can't figure out. @pippinsplugins any thoughts?

<img width="838" alt="screen shot 2017-01-25 at 11 26 13 am" src="https://cloud.githubusercontent.com/assets/36433/22301557/21574864-e2f1-11e6-97d0-3f549c6417c0.png">

**Comment by ghost1227** [comment] 2017-01-25 17:29
Also, knew about the width issue but haven't been able to track down the cause. Thoughts would be appreciated.

**Comment by ghost1227** [comment] 2017-01-25 17:31
@SDavisMedia Thought I should ping you on the tab issue too since that's your baby... Copied the formatting from SL, tab titles don't show.

**Comment by pippinsplugins** [comment] 2017-01-25 17:35
@ghost1227 ignore that issue. It's a known issue that is happening because we haven't incremented version numbers in core yet. Test against master for now please.

**Comment by ghost1227** [comment] 2017-01-25 17:40
That makes sense! Roger that!

**Comment by ghost1227** [comment] 2017-01-25 17:44
Ok, the width issue exists in _some_ state if any of the card content changes. Even simply changing the link text from `Edit Commission` to `Cancel Edit` triggers a width change.

**Comment by ghost1227** [comment] 2017-01-25 17:46
@pippinsplugins Just checked, the same width/resize issue exists in other cards that have dynamic fields (notably Software Licensing)

**Comment by pippinsplugins** [comment] 2017-01-25 18:30
@ghost1227 how about hard-coding the width of the left column? That should fix it.

**Comment by ghost1227** [comment] 2017-01-25 18:37
@pippinsplugins I'd thought about that. Do we want to do it through css or inline? Inline means we have to adjust other tables, but adding it to our CSS could screw with things we don't want to if we don't target specifically enough.

**Comment by pippinsplugins** [comment] 2017-01-25 18:40
CSS please

**Comment by ghost1227** [comment] 2017-01-25 20:26
Fixed the CSS bug [here](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5414)

**Comment by ghost1227** [comment] 2017-01-25 20:26
@pippinsplugins

**Comment by SDavisMedia** [comment] 2017-01-25 23:38
This card view doesn't appear to be complete in terms of matching the new structure. Look at the border inconsistency here:

![screenshot 2017-01-25 15 38 05](https://cloud.githubusercontent.com/assets/2359131/22314009/519d3f9c-e314-11e6-8696-9b930a26690c.png)

Give me a second to look into what's wrong there as well as the page jump PR for EDD core.

**Comment by SDavisMedia** [comment] 2017-01-25 23:51
Ignore that. ^^^ All good here. I had problems pulling down.

**Comment by SDavisMedia** [comment] 2017-01-26 00:50
I'm not sure I like the tab titles. One of the goals of this new view is to actually show tab text but also make the overall page easier to follow. In introducing the full page title, it allows us to be brief on the tabs.

Like SL: 
![screenshot 2017-01-25 16 44 57](https://cloud.githubusercontent.com/assets/2359131/22315789/c0cd79be-e31d-11e6-91e3-02b0554618e3.png)


And FES:
![screenshot 2017-01-25 16 45 41](https://cloud.githubusercontent.com/assets/2359131/22315786/ba5a6dee-e31d-11e6-8528-1dfae2b2a3a6.png)

Here's Commissions at the moment:
![screenshot 2017-01-25 16 43 50](https://cloud.githubusercontent.com/assets/2359131/22315804/ccb927c8-e31d-11e6-8bbe-4858f0241011.png)

Since `Commission Details` is already leading the page, I'd like to see those tabs adjusted to simply `Overview` and `Delete`.

The full context is easily visible for anyone reading the page. For accessibility, the full text is already built into the markup through attributes for screen readers, so no need to show it: https://github.com/easydigitaldownloads/EDD-Commissions/commit/2b90c02c6047d9ca1ab26f838725787ea404d447#diff-11e3350304b45260a616dca1ee650c50R235

**Comment by SDavisMedia** [comment] 2017-01-26 00:52
And also a different icon for the top tab there. I think the lock was carried over from SL.

**Comment by ghost1227** [comment] 2017-01-26 03:11
@SDavisMedia You're right, the lock was a carry over. I also set up the text before actually considering the title tabs. I haven't reworked yet, but I know it needs to be done. Definitely up for ideas on a 'good' icon for the main tab!

**Comment by SDavisMedia** [comment] 2017-01-26 04:24
@ghost1227 okay sweet deal! 

Wow, man... the dashicon choices we have are pretty limited. Here's what FES is using for commissions: https://developer.wordpress.org/resource/dashicons/#products It's actually `products`. I guess that makes sense. Probably the best and most relevant choice on the page.

**Comment by pippinsplugins** [comment] 2017-02-09 19:34
This is looking food to me. I'm going to merge for beta.

**Comment by pippinsplugins** [comment] 2017-02-09 19:37
Actually not merging yet. Had a merge conflict.

Could I please get some testing on `issue/148` to make sure I didn't break anything?

**Comment by pippinsplugins** [comment] 2017-02-09 19:39
Nvm, pretty big merge conflict.

@ghost1227 could you please work on resolving the merge conflict?

**Comment by ghost1227** [comment] 2017-02-09 19:55
@pippinsplugins resolved

**Comment by SDavisMedia** [comment] 2017-02-09 20:37
All's good on my end. :+1:

**Comment by mintplugins** [comment] 2017-02-10 16:02
Testing...

**Comment by mintplugins** [comment] 2017-02-10 16:10
I must be doing something wrong. The layout is not right and the "Edit Commission" link appears to do nothing when clicked. 

I have cleared my cache and pulled the 2.7 branch of edd. 

<img width="784" alt="screen shot 2017-02-10 at 11 09 00 am" src="https://cloud.githubusercontent.com/assets/1638128/22833895/7750a34a-ef81-11e6-8525-e12ab2a8b6cc.png">

**Comment by ghost1227** [comment] 2017-02-10 16:12
@mintplugins you don't have `SCRIPT_DEBUG` enabled do you? 😉

**Comment by mintplugins** [comment] 2017-02-10 16:31
Not sure why but I can't get it to work in Chrome. However in Safari and Firefox it's perfect. If it's working in Chrome for you guys then it's likely my Chrome being weird.

**Comment by pippinsplugins** [comment] 2017-02-10 17:40
Works for me in Chrome.

**Comment by ghost1227** [comment] 2017-02-10 17:41
@pippinsplugins It works for me in all three

**Comment by pippinsplugins** [comment] 2017-02-13 20:32
Merged!

**Comment by ghost1227** [comment] 2017-02-13 22:02
In the change, we somehow lost the Generate Payout File button

**Comment by pippinsplugins** [comment] 2017-02-13 22:43
Merged again.

**Comment by cklosowski** [comment] 2017-02-20 23:11
Re-opening just to get some testing done once #178 is done.

**Comment by pippinsplugins** [comment] 2017-02-21 15:26
This looks good on `issue/178` to me.

**Comment by SDavisMedia** [comment] 2017-02-21 15:38
Is there a reason why when adding a new commission record with the Add New button, you don't get to set the commissions Type (flat / percentage)? We record the Type in the commission meta as `percentage`.

**Comment by pippinsplugins** [comment] 2017-02-21 15:45
We should definitely have that option.

**Comment by SDavisMedia** [comment] 2017-02-21 15:46
EDIT: Actually, it looks like there's different behavior between `issue/178` and `issue/148`.

`issue/178`:
```
a:5:{s:7:"user_id";i:1;s:4:"rate";s:2:"55";s:6:"amount";s:5:"55.00";s:8:"currency";s:3:"USD";s:4:"type";s:10:"percentage";}
```

`issue/178`
```
a:4:{s:7:"user_id";i:1;s:4:"rate";s:2:"35";s:6:"amount";s:5:"35.00";s:8:"currency";s:3:"USD";}
```

**Comment by SDavisMedia** [comment] 2017-02-21 15:47
Also, there's a field for Payment ID but I don't see it doing anything. When you add a payment ID. It doesn't display a connection to an existing payment record on the commissions table. What is this field for?

**Comment by SDavisMedia** [comment] 2017-02-21 18:57
@cklosowski working well for me now. The commission type UI works perfectly and the selection is being saved properly. :+1:

**Closed** 2017-02-21 20:36 UTC
Labels: Enhancement
