### ISSUE TITLE
Make batch payouts use commission currency. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Commissions#176] opened 2017-01-05 21:47 UTC
When generating a batch payout in EDD_Batch_Commissions_Payout, if your commissions happen to have different currencies, all commissions are generated to have the same currency because of the customer's key in the array. 

If the key was set to combine the user's email and the currency of the payment, a separate payout could be generated for each currency. 

https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/admin/class-batch-commissions-payout.php#L96

**Comment by mintplugins** [comment] 2017-01-07 03:21
https://secure.helpscout.net/conversation/300213985/50215/

**Comment by pippinsplugins** [comment] 2017-01-31 21:45
I _think_ the PR is right but need to test to confirm.

**Comment by ghost1227** [comment] 2017-01-31 21:48
It works in my tests (assuming one currency), but I'll admit I haven't tested against multiple currencies for a given user.

**Comment by pippinsplugins** [comment] 2017-01-31 22:09
@ghost1227 please go ahead and set up a multi currency test.

**Comment by ghost1227** [comment] 2017-02-02 19:45
Works for me!

**Comment by pippinsplugins** [comment] 2017-02-02 22:20
@mintplugins could you test the  PR as well?

**Comment by mintplugins** [comment] 2017-02-10 15:58
@ghost1227 What did you do to test this with multiple currencies. Can you give me the steps to test?

**Comment by ghost1227** [comment] 2017-02-13 21:44
@mintplugins is experiencing the issue presented in https://github.com/easydigitaldownloads/EDD-Commissions/issues/79 while testing this. He is going to review the referenced issue since I'm unable to reproduce it.

**Comment by mintplugins** [comment] 2017-02-14 15:41
@ghost1227 I tracked the issue down to the addition of the edd_commissions_load() function which is hooked to plugins_loaded at priority 11. 

The hook in EDD called edd_register_batch_exporters is also hooked to plugins_loaded at priority 10. 

Thus, the hook which includes the EDD_Batch_Commissions_Payout class never actually fires and so it is not included when it is needed. 

I tried changing the priority on edd_commissions_load to 10 and also just removing the priority. Unfortunately, that does not fix the issue either as edd_register_batch_exporters is obviously still running first. 

Thus I propose we change the priority of edd_register_batch_exporters to 99 to be sure all includes hooked to plugins_loaded have actually fired before we set up the batch exporters. EDD Core issue logged here:

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5465

**Comment by mintplugins** [comment] 2017-02-14 15:51
Back on track for this issue, as I mentioned, to test this issue I changed the priority of that hook to 99 in EDD Core and am now able to export payout files. 

The payout files are using the correct currency:
<img width="314" alt="screen shot 2017-02-14 at 10 48 38 am" src="https://cloud.githubusercontent.com/assets/1638128/22936381/5667b8ce-f2a3-11e6-8fc2-2e4855efde8b.png">
<img width="368" alt="screen shot 2017-02-14 at 10 50 14 am" src="https://cloud.githubusercontent.com/assets/1638128/22936404/66c1e280-f2a3-11e6-97fc-4c53bc9b0fd2.png">

Now that I see this, I feel like we also need to make sure that the correct commission is shown in the list of commissions in wp-admin as well:

Note these are all Pounds and some should be Dollars:
<img width="1267" alt="screen shot 2017-02-14 at 10 51 00 am" src="https://cloud.githubusercontent.com/assets/1638128/22936448/8eafa4a8-f2a3-11e6-9eac-847c4fa08131.png">

**Comment by mintplugins** [comment] 2017-02-14 15:55
Perhaps an unrelated issue as well, the amounts in the payout file do not match the amounts in wp-admin. Also, while there are 6 commissions in wp-admin, there are only 4 in the batch payout file. I made sure to check that my date range covered all commissions.

**Comment by SDavisMedia** [comment] 2017-02-15 05:58
I'm not quite sure where this stands at the moment but I'm trying to generate a payout file that will include multiple currencies and I run into admin-ajax.php errors on `issue/176`. Can't replicate on `master`. Why would that be?

![image 2017-02-14 at 9 56 54 pm](https://cloud.githubusercontent.com/assets/2359131/22962276/c4252ba0-f300-11e6-8e1f-c200d00c52fd.png)

**Comment by mintplugins** [comment] 2017-02-15 18:07
@SDavisMedia You can now just pull laster master of EDD core and it should resolve that so you can generate a payout.

**Comment by cklosowski** [comment] 2017-02-16 22:09
I'm going to get `master` merged in here as well to make the setup process easier while testing on a fresh site.

**Comment by cklosowski** [comment] 2017-02-16 22:43
@easydigitaldownloads/core-devs are we expecting this to work with the EDD Currency Converter plugin? Or is this something that the store currency has to be set for?

I had assume currency converter would actually handle this...and I think customer's might as well, just want to make sure.

**Comment by cklosowski** [comment] 2017-02-16 22:47
This seems to be working well. I agree that we shoudl open up a new issue to also expose this data in the list table.

**Comment by cklosowski** [comment] 2017-02-16 22:47
Thoughts on if we should fix the list table now or later? @pippinsplugins @mintplugins @ghost1227

**Comment by pippinsplugins** [comment] 2017-02-17 02:46
Let's fix it later.

**Comment by mintplugins** [comment] 2017-02-17 03:31
Testing again - this wasn't working properly for me last time...

**Comment by mintplugins** [comment] 2017-02-17 03:47
Okay nevermind - this is all working great for me now 👍

**Comment by cklosowski** [comment] 2017-02-17 17:45
I'm merging `release/3.3` back into this and waiting for unit tests to pass. once it passes I'll merge 🎉

**Closed** 2017-02-17 17:51 UTC
Labels: bug, Has PR, Needs Testing
