### ISSUE TITLE
PHP Strict Error in render_formbuilder_field()

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Commissions#91] opened 2015-10-28 14:01 UTC
I get this PHP strict notice in the admin on the latest version of Commissions.
```
PHP Strict Standards:  Declaration of FES_Commissions_Email_Field::render_formbuilder_field() should be compatible with FES_Field::render_formbuilder_field($index = -2, $insert = false) in /wp-content/plugins/edd-commissions/includes/commissions-email-field.php on line 143
```

**Comment by chriscct7** [comment] 2015-10-28 17:50
This is a duplicate of https://github.com/easydigitaldownloads/EDD-Commissions/pull/90, which fixed this. Someone just needs to push it out.

**Closed by chriscct7** 2015-10-28 17:50 UTC
Labels: bug
