### ISSUE TITLE
Back Pagination Links Don't Work on Unpaid Commissions

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#83] opened 2015-08-14 14:42 UTC
On page 7, this is the link for page 6:
https://easydigitaldownloads.com/your-account/&eddcup=6?eddcup=7

Could affect paid and other pagination links as well

**Comment by ghost1227** [comment] 2017-02-07 16:52
I can't replicate this either locally or on the EDD site, @pippinsplugins have you actually seen this?

**Comment by ghost1227** [comment] 2017-02-13 16:53
Since this can't be reproduced (at least anymore) I'm closing as invalid

**Comment by cklosowski** [comment] 2017-10-12 03:24
going to actually close it this time :)

**Closed by cklosowski** 2017-10-12 03:24 UTC
Labels: Bug, invalid
