### ISSUE TITLE
Admin responsive issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#218] opened 2017-04-14 16:27 UTC
Following on from my responsive issues post on the core EDD Github, I've discovered some responsive issues with the commissions plugin.

Alignment/margin on add new commission button.

![commissions - add new button](https://cloud.githubusercontent.com/assets/22668877/25048897/e86eb800-2136-11e7-9128-2859687e3abe.png)

Checkbox width issue on commissions overview table.

![commissions - commissions overview](https://cloud.githubusercontent.com/assets/22668877/25048917/fc6feec8-2136-11e7-9dbd-9e683ba6049d.png)

Issue with select widths, radio button margins/spacing, etc.

![commissions - edit screen](https://cloud.githubusercontent.com/assets/22668877/25048938/11bafe1c-2137-11e7-869f-5463f75a92e8.png)

On the product add/edit screen, the new commissions metabox section has width issues. Would probably look best stacked.

![commissions - product edit screen](https://cloud.githubusercontent.com/assets/22668877/25048961/29f69932-2137-11e7-82be-4ad299b7516f.png)

**Comment by cklosowski** [comment] 2017-06-14 21:32
The Cutoff checkbox is an EDD Core issue. It's caused by this:
```
	#edd-item-card-wrapper .widefat td, .widefat th {
		padding: 4px 6px;
		max-width: 100px!important;
		display: table-cell;
		overflow: hidden;
	}
```
Removing the `overflow: hidden;` fixes that. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5812

**Comment by cklosowski** [comment] 2017-06-14 22:04
widths of inputs in `item-info` wrappers need to be done in core too, this will fix it for not just Commissions but all addons that are using the new item-info wrappers

**Comment by cklosowski** [comment] 2017-06-14 22:41
Ok i've made some changes here...but in order to just avoid the inevitable...i've merge in #134 into this branch since that's getting close to release, and a bunch of work has been redone already.

Should have fixed up a bunch of the issues, along with the ones fixed in EDD Core (mentioned above).

**Comment by pippinsplugins** [comment] 2017-07-05 16:47
@cklosowski possible to fix the overlap of the user selector in the download edit screen metabox?

**Comment by cklosowski** [comment] 2017-07-05 17:03
I'm not seeing that, on latest EDD `release/2.8`? We had some of the issues that were in EDD Core styles, not Commissions styles.

**Comment by cklosowski** [comment] 2017-07-05 17:54
@pippinsplugins I think I see what you're talking about. I can't seem to get any CSS to affect it since it's using the WP List table styles...but I'm wondering if we just wait for EDD 2.8 to release and we just then adopt the no table model that we're using for the repeatable fields in variable prices.

**Comment by pippinsplugins** [comment] 2017-07-05 18:26
This is what I'm referring to:

<img width="389" alt="screen shot 2017-07-05 at 1 26 35 pm" src="https://user-images.githubusercontent.com/1034109/27878935-97f51d6c-6185-11e7-87dd-a05a336d1eb5.png">

**Comment by cklosowski** [comment] 2017-07-05 18:28
Yeah, I cannot get that to fix, due to WP Core styles, and that's one of
the major reasons we re-wrote that code in EDD Core. I think we should just
wait until 2.8 is out and redo that whole section with the divs instead of
tables.

**Comment by pippinsplugins** [comment] 2017-07-05 18:29
I'm fine with that.

**Closed** 2017-07-05 18:41 UTC
Labels: bug
