### ISSUE TITLE
Add support for commissions on renewal payments in EDD Recurring

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#102] opened 2015-12-23 02:05 UTC
Commissions are currently only recorded on the first payment in an EDD subscription. We should add an option to record a commission on renewal payments too.

**Comment by michaelbeil** [comment] 2016-09-15 18:52
A request: https://secure.helpscout.net/conversation/251538138/42439/?folderId=725711

Related: #113

**Comment by cklosowski** [comment] 2017-02-07 22:15
Closing as a duplicate of #113. Work was already started there.

**Closed by cklosowski** 2017-02-07 22:15 UTC
Labels: duplicate, enhancement
